#!/bin/sh

WORKSPACE="$(dirname "$0")"

case "$1" in
format)
	shift
	exec devcontainer exec --workspace-folder "$WORKSPACE" tools/format.sh "$@"
	;;
lint)
	shift
	exec devcontainer exec --workspace-folder "$WORKSPACE" tools/lint.sh "$@"
	;;
docs)
	shift
	exec devcontainer exec --workspace-folder "$WORKSPACE" tools/docs.sh "$@"
	;;
*)
	exec devcontainer exec --workspace-folder "$WORKSPACE" "$@"
	;;
esac
