name: Docs

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate examples page
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/p4kt-devcontainer
          runCmd: tools/generate_examples_doc.sh

      - name: Build docs
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/qobilidop/p4kt-devcontainer
          runCmd: mkdocs build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - id: deployment
        uses: actions/deploy-pages@v4
